modLoader="javafml"
loaderVersion="[4,)"
license="Apache License version 2.0"

[[mods]]
modId="custom_clear_lag"
version="1.0.4"
displayName="Custom Clear Lag"
displayURL="https://github.com/Dreyka-Oas/CustomClearLag.git"
logoFile="logo.png"
credits="Developed by Dreyka Oas. Thank you to everyone who supports modding and the Minecraft community! \u2764\uFE0F"
authors="Dreyka Oas"
description="Entity Management \u2694\uFE0F\u2728"

# Start of user code block mod configuration
# End of user code block mod configuration

[[dependencies.custom_clear_lag]]
    modId="neoforge"
    type="required"
    versionRange="[21.1.65,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.custom_clear_lag]]
    modId="minecraft"
    type="required"
    versionRange="[1.21.1]"
    ordering="AFTER"
    side="BOTH"




# Start of user code block dependencies configuration
# End of user code block dependencies configuration