modLoader="javafml"
loaderVersion="[4,)"
license="Not specified"

[[mods]]
modId="custom_clear_lag"
version="1.0.0"
displayName="Custom Clear Lag"
displayURL="https://mcreator.net"
credits="Created using mod maker MCreator - https://mcreator.net/about"
authors="dreyka-oas, MCreator"

# Start of user code block mod configuration
# End of user code block mod configuration

[[dependencies.custom_clear_lag]]
    modId="neoforge"
    type="required"
    versionRange="[21.1.12,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.custom_clear_lag]]
    modId="minecraft"
    type="required"
    versionRange="[1.21.1]"
    ordering="AFTER"
    side="BOTH"




# Start of user code block dependencies configuration
# End of user code block dependencies configuration