modLoader="javafml"
loaderVersion="[4,)"
license="Apache License version 2.0"

[[mods]]
modId="custom_clear_lag"
version="1.0.9"
displayName="Custom Clear Lag"
displayURL="https://github.com/Dreyka-Oas/CustomClearLag.git"
logoFile="logo.png"
credits="O.A.S"
authors="Dreyka Oas"
description="Entity Management"

# Start of user code block mod configuration
# End of user code block mod configuration

[[dependencies.custom_clear_lag]]
    modId="neoforge"
    type="required"
    versionRange="[21.4.101-beta,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.custom_clear_lag]]
    modId="minecraft"
    type="required"
    versionRange="[1.21.4]"
    ordering="AFTER"
    side="BOTH"




# Start of user code block dependencies configuration
# End of user code block dependencies configuration