modLoader="javafml"
loaderVersion="[4,)"
license="Apache License version 2.0"

[[mods]]
modId="custom_clear_lag"
version="0.0.1"
displayName="Custom Clear Lag"
displayURL="https://github.com/Dreyka-Oas/CustomClearLag.git"
logoFile="logo.png"
credits="D\u00E9velopp\u00E9 par Dreyka Oas. Merci \u00E0 tous ceux qui soutiennent le modding et la communaut\u00E9 Minecraft ! \u2764\uFE0F"
authors="Dreyka Oas"
description="Entity Management \u2694\uFE0F\u2728"

# Start of user code block mod configuration
# End of user code block mod configuration

[[dependencies.custom_clear_lag]]
    modId="neoforge"
    type="required"
    versionRange="[21.1.12,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.custom_clear_lag]]
    modId="minecraft"
    type="required"
    versionRange="[1.21.1]"
    ordering="AFTER"
    side="BOTH"




# Start of user code block dependencies configuration
# End of user code block dependencies configuration